/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhapiStartConversationRouteImport } from './routes/api/whapi/start-conversation'
import { Route as ApiWhapiSendRouteImport } from './routes/api/whapi/send'
import { Route as ApiPublicWhapiWebhookRouteImport } from './routes/api/public/whapi-webhook'
import { Route as ApiPublicAcceptInviteRouteImport } from './routes/api/public/accept-invite'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhapiStartConversationRoute =
  ApiWhapiStartConversationRouteImport.update({
    id: '/api/whapi/start-conversation',
    path: '/api/whapi/start-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhapiSendRoute = ApiWhapiSendRouteImport.update({
  id: '/api/whapi/send',
  path: '/api/whapi/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhapiWebhookRoute = ApiPublicWhapiWebhookRouteImport.update({
  id: '/api/public/whapi-webhook',
  path: '/api/public/whapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcceptInviteRoute = ApiPublicAcceptInviteRouteImport.update({
  id: '/api/public/accept-invite',
  path: '/api/public/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/whapi/send': typeof ApiWhapiSendRoute
  '/api/whapi/start-conversation': typeof ApiWhapiStartConversationRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/whapi/send': typeof ApiWhapiSendRoute
  '/api/whapi/start-conversation': typeof ApiWhapiStartConversationRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/api/public/accept-invite': typeof ApiPublicAcceptInviteRoute
  '/api/public/whapi-webhook': typeof ApiPublicWhapiWebhookRoute
  '/api/whapi/send': typeof ApiWhapiSendRoute
  '/api/whapi/start-conversation': typeof ApiWhapiStartConversationRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/settings'
    | '/team'
    | '/api/public/accept-invite'
    | '/api/public/whapi-webhook'
    | '/api/whapi/send'
    | '/api/whapi/start-conversation'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/settings'
    | '/team'
    | '/api/public/accept-invite'
    | '/api/public/whapi-webhook'
    | '/api/whapi/send'
    | '/api/whapi/start-conversation'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/settings'
    | '/team'
    | '/api/public/accept-invite'
    | '/api/public/whapi-webhook'
    | '/api/whapi/send'
    | '/api/whapi/start-conversation'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  ApiPublicAcceptInviteRoute: typeof ApiPublicAcceptInviteRoute
  ApiPublicWhapiWebhookRoute: typeof ApiPublicWhapiWebhookRoute
  ApiWhapiSendRoute: typeof ApiWhapiSendRoute
  ApiWhapiStartConversationRoute: typeof ApiWhapiStartConversationRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whapi/start-conversation': {
      id: '/api/whapi/start-conversation'
      path: '/api/whapi/start-conversation'
      fullPath: '/api/whapi/start-conversation'
      preLoaderRoute: typeof ApiWhapiStartConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whapi/send': {
      id: '/api/whapi/send'
      path: '/api/whapi/send'
      fullPath: '/api/whapi/send'
      preLoaderRoute: typeof ApiWhapiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whapi-webhook': {
      id: '/api/public/whapi-webhook'
      path: '/api/public/whapi-webhook'
      fullPath: '/api/public/whapi-webhook'
      preLoaderRoute: typeof ApiPublicWhapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-invite': {
      id: '/api/public/accept-invite'
      path: '/api/public/accept-invite'
      fullPath: '/api/public/accept-invite'
      preLoaderRoute: typeof ApiPublicAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  ApiPublicAcceptInviteRoute: ApiPublicAcceptInviteRoute,
  ApiPublicWhapiWebhookRoute: ApiPublicWhapiWebhookRoute,
  ApiWhapiSendRoute: ApiWhapiSendRoute,
  ApiWhapiStartConversationRoute: ApiWhapiStartConversationRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
